-- verify_schema.sql
-- Run in the Supabase SQL Editor any time. Returns one row per table or column the app needs
-- that your database does not have. Zero rows = the schema is complete.
-- A row here means a migration was skipped or ran against an older table: run the migration
-- files again in order (they are safe to re-run).

with expected(table_name, column_name) as (values
  ('businesses','id'),
  ('businesses','owner_id'),
  ('businesses','name'),
  ('businesses','wa_phone_number_id'),
  ('businesses','wa_owner_number'),
  ('businesses','created_at'),
  ('businesses','updated_at'),
  ('businesses','auto_reply'),
  ('businesses','business_facts'),
  ('businesses','tone_notes'),
  ('businesses','cold_after_days'),
  ('businesses','payment_details'),
  ('businesses','follow_up_settings'),
  ('businesses','wa_access_token'),
  ('businesses','wa_app_secret'),
  ('businesses','wa_verify_token'),
  ('businesses','reply_mode'),
  ('draft_replies','id'),
  ('draft_replies','lead_id'),
  ('draft_replies','business_id'),
  ('draft_replies','body'),
  ('draft_replies','order_status'),
  ('draft_replies','order_summary'),
  ('draft_replies','created_at'),
  ('draft_replies','order_lines'),
  ('draft_replies','order_total_myr'),
  ('feedback','id'),
  ('feedback','business_id'),
  ('feedback','lead_id'),
  ('feedback','rating'),
  ('feedback','comment'),
  ('feedback','created_at'),
  ('follow_ups','id'),
  ('follow_ups','business_id'),
  ('follow_ups','lead_id'),
  ('follow_ups','kind'),
  ('follow_ups','status'),
  ('follow_ups','due_at'),
  ('follow_ups','sent_at'),
  ('follow_ups','detail'),
  ('follow_ups','campaign'),
  ('follow_ups','template_name'),
  ('follow_ups','body'),
  ('follow_ups','order_key'),
  ('follow_ups','created_at'),
  ('inbound_jobs','id'),
  ('inbound_jobs','business_id'),
  ('inbound_jobs','lead_id'),
  ('inbound_jobs','status'),
  ('inbound_jobs','attempts'),
  ('inbound_jobs','run_after'),
  ('inbound_jobs','locked_until'),
  ('inbound_jobs','last_error'),
  ('inbound_jobs','created_at'),
  ('inbound_jobs','updated_at'),
  ('knowledge_entries','id'),
  ('knowledge_entries','business_id'),
  ('knowledge_entries','category'),
  ('knowledge_entries','title'),
  ('knowledge_entries','content'),
  ('knowledge_entries','created_at'),
  ('knowledge_entries','updated_at'),
  ('knowledge_entries','price_myr'),
  ('leads','id'),
  ('leads','business_id'),
  ('leads','wa_contact_number'),
  ('leads','order_lines'),
  ('leads','order_total_myr'),
  ('leads','name'),
  ('leads','need'),
  ('leads','budget_myr'),
  ('leads','deadline'),
  ('leads','stage'),
  ('leads','language'),
  ('leads','last_message_at'),
  ('leads','last_inbound_at'),
  ('leads','last_outbound_at'),
  ('leads','created_at'),
  ('leads','updated_at'),
  ('leads','quoted_price_myr'),
  ('leads','locked_fields'),
  ('leads','pending_decision'),
  ('leads','human_reason'),
  ('leads','last_chased_at'),
  ('leads','bot_paused_until'),
  ('leads','handoff_note'),
  ('leads','order_status'),
  ('leads','order_summary'),
  ('leads','follow_up_consent'),
  ('leads','consent_asked_at'),
  ('leads','awaiting_feedback'),
  ('leads','paid_at'),
  ('messages','id'),
  ('messages','lead_id'),
  ('messages','business_id'),
  ('messages','wa_message_id'),
  ('messages','direction'),
  ('messages','body'),
  ('messages','source'),
  ('messages','sent_at'),
  ('messages','created_at'),
  ('subscriptions','id'),
  ('subscriptions','business_id'),
  ('subscriptions','stripe_customer_id'),
  ('subscriptions','stripe_subscription_id'),
  ('subscriptions','plan'),
  ('subscriptions','status'),
  ('subscriptions','trial_ends_at'),
  ('subscriptions','current_period_end'),
  ('subscriptions','created_at'),
  ('subscriptions','updated_at')
)
select e.table_name, e.column_name,
       case when not exists (
         select 1 from information_schema.tables t
         where t.table_schema = 'public' and t.table_name = e.table_name
       ) then 'table missing' else 'column missing' end as problem
from expected e
where not exists (
  select 1 from information_schema.columns c
  where c.table_schema = 'public' and c.table_name = e.table_name and c.column_name = e.column_name
)
order by e.table_name, e.column_name;
