// GENERATED by scripts/gen-db-types.mjs from the migrations. Do not edit by hand.
// Regenerate after adding a migration; CI fails if this file is out of date.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      businesses: {
        Row: {
          id: string;
          owner_id: string;
          name: string;
          wa_phone_number_id: string | null;
          wa_owner_number: string | null;
          created_at: string;
          updated_at: string;
          auto_reply: boolean;
          business_facts: string | null;
          tone_notes: string | null;
          cold_after_days: number;
          payment_details: string | null;
          follow_up_settings: Json;
          wa_access_token: string | null;
          wa_app_secret: string | null;
          wa_verify_token: string | null;
          reply_mode: string;
        };
        Insert: {
          id?: string;
          owner_id: string;
          name: string;
          wa_phone_number_id?: string | null;
          wa_owner_number?: string | null;
          created_at?: string;
          updated_at?: string;
          auto_reply?: boolean;
          business_facts?: string | null;
          tone_notes?: string | null;
          cold_after_days?: number;
          payment_details?: string | null;
          follow_up_settings?: Json;
          wa_access_token?: string | null;
          wa_app_secret?: string | null;
          wa_verify_token?: string | null;
          reply_mode?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          name?: string;
          wa_phone_number_id?: string | null;
          wa_owner_number?: string | null;
          created_at?: string;
          updated_at?: string;
          auto_reply?: boolean;
          business_facts?: string | null;
          tone_notes?: string | null;
          cold_after_days?: number;
          payment_details?: string | null;
          follow_up_settings?: Json;
          wa_access_token?: string | null;
          wa_app_secret?: string | null;
          wa_verify_token?: string | null;
          reply_mode?: string;
        };
        Relationships: [
          {
            foreignKeyName: "businesses_owner_id_fkey";
            columns: ["owner_id"];
            isOneToOne: false;
            referencedRelation: "auth.users";
            referencedColumns: ["id"];
          },
        ];
      };
      draft_replies: {
        Row: {
          id: string;
          lead_id: string;
          business_id: string;
          body: string;
          order_status: string | null;
          order_summary: string | null;
          created_at: string;
          order_lines: Json | null;
          order_total_myr: number | null;
        };
        Insert: {
          id?: string;
          lead_id: string;
          business_id: string;
          body: string;
          order_status?: string | null;
          order_summary?: string | null;
          created_at?: string;
          order_lines?: Json | null;
          order_total_myr?: number | null;
        };
        Update: {
          id?: string;
          lead_id?: string;
          business_id?: string;
          body?: string;
          order_status?: string | null;
          order_summary?: string | null;
          created_at?: string;
          order_lines?: Json | null;
          order_total_myr?: number | null;
        };
        Relationships: [
          {
            foreignKeyName: "draft_replies_business_id_fkey";
            columns: ["business_id"];
            isOneToOne: false;
            referencedRelation: "businesses";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "draft_replies_lead_id_fkey";
            columns: ["lead_id"];
            isOneToOne: false;
            referencedRelation: "leads";
            referencedColumns: ["id"];
          },
        ];
      };
      feedback: {
        Row: {
          id: string;
          business_id: string;
          lead_id: string;
          rating: number | null;
          comment: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          lead_id: string;
          rating?: number | null;
          comment?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          lead_id?: string;
          rating?: number | null;
          comment?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "feedback_business_id_fkey";
            columns: ["business_id"];
            isOneToOne: false;
            referencedRelation: "businesses";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "feedback_lead_id_fkey";
            columns: ["lead_id"];
            isOneToOne: false;
            referencedRelation: "leads";
            referencedColumns: ["id"];
          },
        ];
      };
      follow_ups: {
        Row: {
          id: string;
          business_id: string;
          lead_id: string;
          kind: string;
          status: string;
          due_at: string;
          sent_at: string | null;
          detail: string | null;
          campaign: string | null;
          template_name: string | null;
          body: string | null;
          order_key: string | null;
          created_at: string;
          claimed_at: string | null;
        };
        Insert: {
          id?: string;
          business_id: string;
          lead_id: string;
          kind: string;
          status?: string;
          due_at: string;
          sent_at?: string | null;
          detail?: string | null;
          campaign?: string | null;
          template_name?: string | null;
          body?: string | null;
          order_key?: string | null;
          created_at?: string;
          claimed_at?: string | null;
        };
        Update: {
          id?: string;
          business_id?: string;
          lead_id?: string;
          kind?: string;
          status?: string;
          due_at?: string;
          sent_at?: string | null;
          detail?: string | null;
          campaign?: string | null;
          template_name?: string | null;
          body?: string | null;
          order_key?: string | null;
          created_at?: string;
          claimed_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "follow_ups_business_id_fkey";
            columns: ["business_id"];
            isOneToOne: false;
            referencedRelation: "businesses";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "follow_ups_lead_id_fkey";
            columns: ["lead_id"];
            isOneToOne: false;
            referencedRelation: "leads";
            referencedColumns: ["id"];
          },
        ];
      };
      inbound_jobs: {
        Row: {
          id: string;
          business_id: string;
          lead_id: string;
          status: string;
          attempts: number;
          run_after: string;
          locked_until: string | null;
          last_error: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          lead_id: string;
          status?: string;
          attempts?: number;
          run_after?: string;
          locked_until?: string | null;
          last_error?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          lead_id?: string;
          status?: string;
          attempts?: number;
          run_after?: string;
          locked_until?: string | null;
          last_error?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "inbound_jobs_business_id_fkey";
            columns: ["business_id"];
            isOneToOne: false;
            referencedRelation: "businesses";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "inbound_jobs_lead_id_fkey";
            columns: ["lead_id"];
            isOneToOne: false;
            referencedRelation: "leads";
            referencedColumns: ["id"];
          },
        ];
      };
      knowledge_documents: {
        Row: {
          id: string;
          business_id: string;
          file_name: string;
          size_bytes: number;
          page_count: number;
          content: string;
          truncated: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          file_name: string;
          size_bytes?: number;
          page_count?: number;
          content: string;
          truncated?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          file_name?: string;
          size_bytes?: number;
          page_count?: number;
          content?: string;
          truncated?: boolean;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "knowledge_documents_business_id_fkey";
            columns: ["business_id"];
            isOneToOne: false;
            referencedRelation: "businesses";
            referencedColumns: ["id"];
          },
        ];
      };
      knowledge_entries: {
        Row: {
          id: string;
          business_id: string;
          category: string;
          title: string;
          content: string;
          created_at: string;
          updated_at: string;
          price_myr: number | null;
        };
        Insert: {
          id?: string;
          business_id: string;
          category: string;
          title: string;
          content: string;
          created_at?: string;
          updated_at?: string;
          price_myr?: number | null;
        };
        Update: {
          id?: string;
          business_id?: string;
          category?: string;
          title?: string;
          content?: string;
          created_at?: string;
          updated_at?: string;
          price_myr?: number | null;
        };
        Relationships: [
          {
            foreignKeyName: "knowledge_entries_business_id_fkey";
            columns: ["business_id"];
            isOneToOne: false;
            referencedRelation: "businesses";
            referencedColumns: ["id"];
          },
        ];
      };
      leads: {
        Row: {
          id: string;
          business_id: string;
          wa_contact_number: string;
          name: string | null;
          need: string | null;
          budget_myr: number | null;
          deadline: string | null;
          stage: string;
          language: string | null;
          last_message_at: string | null;
          last_inbound_at: string | null;
          last_outbound_at: string | null;
          created_at: string;
          updated_at: string;
          quoted_price_myr: number | null;
          locked_fields: string[];
          pending_decision: boolean;
          human_reason: string | null;
          last_chased_at: string | null;
          bot_paused_until: string | null;
          handoff_note: string | null;
          order_status: string | null;
          order_summary: string | null;
          follow_up_consent: string;
          consent_asked_at: string | null;
          awaiting_feedback: boolean;
          paid_at: string | null;
          order_lines: Json | null;
          order_total_myr: number | null;
        };
        Insert: {
          id?: string;
          business_id: string;
          wa_contact_number: string;
          name?: string | null;
          need?: string | null;
          budget_myr?: number | null;
          deadline?: string | null;
          stage?: string;
          language?: string | null;
          last_message_at?: string | null;
          last_inbound_at?: string | null;
          last_outbound_at?: string | null;
          created_at?: string;
          updated_at?: string;
          quoted_price_myr?: number | null;
          locked_fields?: string[];
          pending_decision?: boolean;
          human_reason?: string | null;
          last_chased_at?: string | null;
          bot_paused_until?: string | null;
          handoff_note?: string | null;
          order_status?: string | null;
          order_summary?: string | null;
          follow_up_consent?: string;
          consent_asked_at?: string | null;
          awaiting_feedback?: boolean;
          paid_at?: string | null;
          order_lines?: Json | null;
          order_total_myr?: number | null;
        };
        Update: {
          id?: string;
          business_id?: string;
          wa_contact_number?: string;
          name?: string | null;
          need?: string | null;
          budget_myr?: number | null;
          deadline?: string | null;
          stage?: string;
          language?: string | null;
          last_message_at?: string | null;
          last_inbound_at?: string | null;
          last_outbound_at?: string | null;
          created_at?: string;
          updated_at?: string;
          quoted_price_myr?: number | null;
          locked_fields?: string[];
          pending_decision?: boolean;
          human_reason?: string | null;
          last_chased_at?: string | null;
          bot_paused_until?: string | null;
          handoff_note?: string | null;
          order_status?: string | null;
          order_summary?: string | null;
          follow_up_consent?: string;
          consent_asked_at?: string | null;
          awaiting_feedback?: boolean;
          paid_at?: string | null;
          order_lines?: Json | null;
          order_total_myr?: number | null;
        };
        Relationships: [
          {
            foreignKeyName: "leads_business_id_fkey";
            columns: ["business_id"];
            isOneToOne: false;
            referencedRelation: "businesses";
            referencedColumns: ["id"];
          },
        ];
      };
      messages: {
        Row: {
          id: string;
          lead_id: string;
          business_id: string;
          wa_message_id: string;
          direction: string;
          body: string | null;
          source: string | null;
          sent_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          lead_id: string;
          business_id: string;
          wa_message_id: string;
          direction: string;
          body?: string | null;
          source?: string | null;
          sent_at: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          lead_id?: string;
          business_id?: string;
          wa_message_id?: string;
          direction?: string;
          body?: string | null;
          source?: string | null;
          sent_at?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "messages_business_id_fkey";
            columns: ["business_id"];
            isOneToOne: false;
            referencedRelation: "businesses";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "messages_lead_id_fkey";
            columns: ["lead_id"];
            isOneToOne: false;
            referencedRelation: "leads";
            referencedColumns: ["id"];
          },
        ];
      };
      subscriptions: {
        Row: {
          id: string;
          business_id: string;
          stripe_customer_id: string | null;
          stripe_subscription_id: string | null;
          plan: string;
          status: string;
          trial_ends_at: string | null;
          current_period_end: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          stripe_customer_id?: string | null;
          stripe_subscription_id?: string | null;
          plan?: string;
          status?: string;
          trial_ends_at?: string | null;
          current_period_end?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          stripe_customer_id?: string | null;
          stripe_subscription_id?: string | null;
          plan?: string;
          status?: string;
          trial_ends_at?: string | null;
          current_period_end?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "subscriptions_business_id_fkey";
            columns: ["business_id"];
            isOneToOne: false;
            referencedRelation: "businesses";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Views: { [_ in never]: never };
    Functions: {
      claim_inbound_jobs: {
        Args: { p_limit?: number; p_lease_seconds?: number; p_max_attempts?: number };
        Returns: Database["public"]["Tables"]["inbound_jobs"]["Row"][];
      };
      last_messages: {
        Args: { p_business_id: string };
        Returns: { lead_id: string; direction: string; body: string | null; sent_at: string; source: string | null }[];
      };
      search_leads_by_message: {
        Args: { p_query: string; p_limit?: number };
        Returns: { lead_id: string }[];
      };
      dashboard_stats: {
        Args: { p_today_start: string; p_tomorrow_start: string; p_now?: string };
        Returns: Json;
      };
    };
    Enums: { [_ in never]: never };
    CompositeTypes: { [_ in never]: never };
  };
};

type PublicSchema = Database["public"];
export type Tables<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Row"];
export type TablesInsert<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Insert"];
export type TablesUpdate<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Update"];
